### ISSUE TITLE
gui-you-get没有WIN  32位系统能用的么？

### ISSUE THREAD

**Issue by lki2019** [ingbyr/GUI-YouGet#10]
gui-you-get没有WIN  32位系统能用的么？

**Comment by ingbyr** [comment]
可以先用这个 https://github.com/MrS0m30n3/youtube-dl-gui ， 我这个坑不知道什么时候能填上了

**Comment by ingbyr** [comment]
[0.2版本](https://github.com/ingbyr/GUI-YouGet/releases) 应该可以了
