### ISSUE TITLE
Get information Failed?

### ISSUE THREAD

**Issue by amwihgu** [ingbyr/GUI-YouGet#11]
"Get Information Failed" error prompts everytime i clicked "Download" Button.
the link i tried with is http://www.bilibili.com/video/av12687879/
Win10 Home, zh-cn, x64

**Comment by ingbyr** [comment]
I will fix it as soon as possible. You can check out the dev branch

**Comment by shirh19910112** [comment]
hi, cloud you help me how to compile a exe file from your source code?

**Comment by shirh19910112** [comment]
![image](https://user-images.githubusercontent.com/17871310/30530835-9bb917d2-9c7c-11e7-97a5-6a6fa8bec254.png)

**Comment by ingbyr** [comment]
Please refer to [compile_linux.sh](https://github.com/ingbyr/GUI-YouGet/blob/master/app/compile_linux.sh) and [pyinstaller](https://pyinstaller.readthedocs.io/en/stable/) @shirh19910112

**Comment by shirh19910112** [comment]
How to compile exe files in Microsoft Windows? It's going wrong when open the exe file. @ingbyr

**Comment by shirh19910112** [comment]
cloud you tell me what version of Python and Pyinstaller do you installed? @ingbyr

**Comment by ingbyr** [comment]
python3.5.
 i can't remember the version of pyinstaller. i think the latest pyinstaller is ok

**Comment by shirh19910112** [comment]
it's seems missing socks module when compile the exe file. using pyinstaller -D main.py to compile files.
![image](https://user-images.githubusercontent.com/17871310/30644490-1d9aad28-9e45-11e7-9227-185dbd54f9c1.png)

@ingbyr

**Comment by ingbyr** [comment]
install pysocks

**Comment by shirh19910112** [comment]
the pysocks is installed in my system, but the error is always there, cloud you tell me how to solve this problem? @ingbyr

**Comment by ingbyr** [comment]
Open a issue at https://github.com/Anorov/PySocks @shirh19910112
