### ISSUE TITLE
界面字体显示不完整

### ISSUE THREAD

**Issue by Caihua528** [ingbyr/GUI-YouGet#13]
![screen](https://user-images.githubusercontent.com/24402924/30956316-7fdf0144-a469-11e7-8dbd-c70c4c576a1c.png)

Win 10的系统，无法完整显示主界面

**Comment by ingbyr** [comment]
是所有界面都有问题吗？可不可以把log/debug.log文件内容发一下？

**Comment by Caihua528** [comment]
[debug.log](https://github.com/ingbyr/GUI-YouGet/files/1340772/debug.log)
请参考，谢谢！

**Comment by ingbyr** [comment]
duplicate of #30

**Comment by ingbyr** [comment]
Duplicate of #30
