### ISSUE TITLE
电脑已经安装了jdk"1.8.0_77 为何还提示 需要安装Java环境

### ISSUE THREAD

**Issue by Codeisfuture** [ingbyr/GUI-YouGet#14]
电脑已经安装了jdk"1.8.0_77 为何还提示 需要安装Java环境

**Comment by ingbyr** [comment]
jdk路径添加到PATH了吗？如果没有可以参考这个
https://docs.oracle.com/javase/8/docs/technotes/guides/install/windows_jdk_install.html#A1097936

**Comment by 247192825** [comment]
直接打开提示“安装java环境”，用命令行运行可以打开
javaw -jar GUI-YouGet.exe
