### ISSUE TITLE
downloading core好像不能正常工作

### ISSUE THREAD

**Issue by megaslx** [ingbyr/GUI-YouGet#15]
两个下载工具没有一个能下载下来的，就算设置了socks代理也是，只能检查到新版本但是无法下载
另外的问题就是我手工下载了youtube-dl替换到core目录里面后再打开工具，工具并不能正常检测目前core的版本。

**Comment by ingbyr** [comment]
发一下 log/debug.log 的内容，还有you-get 0.4.939 版本还没有发布exe文件，导致无法自动更新

**Comment by megaslx** [comment]
又可以下载了。好奇怪。。。
you-get我用python更新了以后copy到core目录可以用。就是gui上面的版本号没变罢了

**Comment by ingbyr** [comment]
版本号可以在app.properties里修改，但不建议手动更新
