### ISSUE TITLE
优酷视频下载速度非常慢，无法下载1080p版本

### ISSUE THREAD

**Issue by Alexanderhanks** [ingbyr/GUI-YouGet#28]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser, but not download them with `GUI-YouGet`.
- [ ] Your `GUI-YouGet` is up-to-date.
- [ ] Your downloading core is up-to-date.
Please paste the full `log/debug.log` inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say(e.g some new features) fill in the box below
> [WRITE SOMETHING]

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器中观看视频，但不能使用`GUI-YouGet`下载。
- [ ] 您的`GUI-YouGet`为最新版。
- [ ] 您的下载引擎为最新版。
 
请将`log/debug.log`文件内容粘贴在下面：

```
[在这里粘贴完整日志]
```

如果您有其他留言（如需要新特性等），请在下面添加：
> [您的留言]

**Comment by ingbyr** [comment]
贴一下日志文件
