### ISSUE TITLE
iqiyi获取到的是广告宣传片

### ISSUE THREAD

**Issue by gameclamp** [ingbyr/GUI-YouGet#3]
http://www.iqiyi.com/v_19rrmakmg4.html#vfrm=2-3-0-1

site: 爱奇艺 (Iqiyi)
title: 广告宣传片
streams: # Available quality and codecs
[ DEFAULT ] _________________________________
- format: suprt-high
  container: f4v
  video-profile: 超高清
  size: 16.4 MiB (17190194 bytes)
  # download-with: you-get --format=suprt-high [URL]
  
  Option is suprt-high
- format: high
  container: f4v
  video-profile: 高清
  size: 6.6 MiB (6946897 bytes)
  # download-with: you-get --format=high [URL]
  
  Option is high
- format: standard
  container: f4v
  video-profile: 标清
  size: 4.3 MiB (4500446 bytes)
  # download-with: you-get --format=standard [URL]
  
  Option is standard
- format: topspeed
  container: f4v
  video-profile: 最差
  size: 1.8 MiB (1862837 bytes)
  # download-with: you-get --format=topspeed [URL]
  
  Option is topspeed

**Comment by ingbyr** [comment]
好的，下个版本会尽量修复
