### ISSUE TITLE
打开GUI-YouGet无法调用Java

### ISSUE THREAD

**Issue by Jeffrey-1996** [ingbyr/GUI-YouGet#32]
一打开GUI-YouGet就会弹出 "This application requires a java runtime environment 1.8.0 - 1.8.0_152"无法使用软件！
不知道怎么解决，求帮助！

**Comment by Baltimore2012** [comment]
分别安装JRE 8U161 和8U162后，运行exe均弹出这个对话框，无法使用。点击对话框后弹出网页仍然要求安装最新版JRE。

**Comment by Jeffrey-1996** [comment]
我后来试了一下，安装了JRE1.8.0_152这个版本，然后可以打开软件了。你可以试试看
