### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by lobster1987** [ingbyr/GUI-YouGet#41]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser, but not download them with `GUI-YouGet`.
- [ ] Your `GUI-YouGet` is up-to-date.
- [ ] Your downloading core is up-to-date.
Please paste the full `app/log/debug.log` inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say(e.g some new features) fill in the box below
> [WRITE SOMETHING]
![xx](https://user-images.githubusercontent.com/15239531/37995920-7b7c2d9c-3272-11e8-8bb2-adfdeb6f8bfa.png)

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器中观看视频，但不能使用`GUI-YouGet`下载。
- [ ] 您的`GUI-YouGet`为最新版。
- [ ] 您的下载引擎为最新版。
 
请将`app/log/debug.log`文件内容粘贴在下面：

```
[在这里粘贴完整日志]
```

如果您有其他留言（如需要新特性等），请在下面添加：
> [您的留言]
#我打开工程，编译出现这个问题，麻烦指点一下怎么解决？

**Comment by ingbyr** [comment]
在工程下新建`app.properties`，内容如下：
```
you-get-version=0.4.985
version=0.2.3
youtube-dl-version=2018.02.26
proxy-port=
proxy-type=
proxy-address=
storage-path=
download-core=youtube-dl
```

**Comment by ingbyr** [comment]
或者把`src/main/deploy`下的`app.properties`拷贝至工程根目录下
